# Generated by Django 6.0.1 on 2026-02-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='gallery_img',
        ),
    ]
