# Generated by Django 6.0.1 on 2026-02-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_gallery_gallery_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='review1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
