# Generated by Django 6.0 on 2026-02-04 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review1'),
    ]

    operations = [
        migrations.CreateModel(
            name='resrve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.IntegerField(null=True)),
                ('number_of_people', models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('request', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
