# Generated by Django 6.0 on 2026-02-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_resrve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resrve',
            old_name='request',
            new_name='request1',
        ),
    ]
