# Generated by Django 6.0 on 2026-02-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_request_resrve_request1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='resrve',
            new_name='reserve',
        ),
    ]
